### ISSUE TITLE
CMS: News Listing (latest)

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/cms-college-main#24]
Using news-group component as a reference, create a component that lists the latest 3 news items.

**Comment by garza-utsa** [comment]
This should be a fairly easy first component for implementation in CAS, the news-group implements this component as a page-picker, this version doesn't need that, as it will only list the latest 3 stories.

**Comment by lalov1** [comment]
Hi @garza-utsa - I think I got a working copy, but please let me know if this isn't what you had in mind:

- https://walledev.it.utsa.edu/entity/open.act?id=39df700381736a1b6bf065e1cf00d3f3&type=format
- https://walledev.it.utsa.edu/entity/open.act?id=d1f631ac81736a1b3be11e06a3a73815&type=page

The only thing I was having problems with is finding the link to view all the articles. I was trying to use the `locatePage` tool, but I couldn't get that to work. Please let me know what your recommendations are to display that link. 

Also, I made any article that is featured to have the `blue-bg`

**Comment by lalov1** [comment]
I got the link working, but there is probably a better way to find the directory instead of hardcoding "prototype": 
`#set($link = $_.locatePage("prototype/news/index").link)`

Let me know if you want me to work on another velocity file.

**Comment by lalov1** [comment]
This has now been completed with the addition of the new data definition header and link fields: 
https://walledev.it.utsa.edu/entity/open.act?id=39df700381736a1b6bf065e1cf00d3f3&type=format
