### ISSUE TITLE
CMS: Faculty Profile Detail Page

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/cms-college-main#34]

**Comment by garza-utsa** [comment]
Work by the web infrastructure - faculty committee/subgroup:

[Elements of Faculty Profile.pdf](https://github.com/utsa-asc/cms-college-main/files/9121836/Elements.of.Faculty.Profile.pdf)

Each subhead should hopefully map to a data definition group.  There is an opportunity to Web 2.0 some of this, as we (UTSA) is using a third party system (UTSA Discovery) to organize this data with faculty.

I'm thinking of a page that has a 1:1 mapping of DD Groups with the above document, but has the ability to either pull in JSON from this third party service, or use the defined WYSIWYG box to show that data instead.  This way, college folks have the option of just using the data already in our system, or providing their own in Cascade.

Using David Akopian as an example:

UTSA Discovery: 
https://utsa.discovery.academicanalytics.com/scholar/stack/11936/DAVID-AKOPIAN?unitId=967&unitType=2

JSON representation:
https://utsa.discovery.academicanalytics.com/api/people/11936

Will need to parse this out and see which structures in this JSON we can map to the groups outlined in the above PDF.

Bare minimum:
- Faculty Page DD will need a field for the JSON link or unique identifier (11936). Alternatively, thinking about making this easy for college communicators, using the public UTSA discovery link and doing some smart parsing to get the UUID.
- Each group should have a radio (use Discovery data or provide your own?)
- If provide your own is selected, then we can show a corresponding WYSIWYG box
- Each of these groups will end up outputting an accordion section
- JS on the page to pull the data and parse out the groups to their respective accordion content sections

Action tasks for planning (John):
- Go thru the above PDF and stub out at least 3 example groups with corresponding titles we can test with (and that have corresponding sections in the JSON)

Actions in CAS (Lallo):
-Begin fleshing out page level data definition that utilizes the existing faculty-block and then this planned functionality
-Attempt grabbing JSON from UTSA Discovery and outputting yes/no radio from cascade

**Comment by lalov1** [comment]
@garza-utsa - Are we able to whitelist some URL's like walledev, so I don't get a CORS error:
![Image](https://user-images.githubusercontent.com/7785251/179838720-820a85d2-f49f-4332-9b90-29b342d785a0.png)

**Comment by garza-utsa** [comment]
booo, CORS, let me reach out the discovery admin

**Comment by garza-utsa** [comment]
oh wait, is this on utsa.discovery.* or do we need to tweak settings on WALLEDEV?

**Comment by lalov1** [comment]
It's when I'm trying to reach the utsa.discovery.* domain. Not sure if they could whitelist *.utsa.edu, which might be enough for it to work on walledev and then production down the line. I'm using the following extension to help me in the interim:
https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf
