### ISSUE TITLE
CMS: Faculty Profile Detail Page link display bug

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/cms-college-main#43]
When no CV (no link) or personal website is given (no link), the two links are still displayed on the profile page

steps to reproduce or example of bug:

https://walledev.it.utsa.edu/entity/open.act?id=d6805a2381736a1b48bb59f115e130aa&type=page

**Comment by lalov1** [comment]
I added a check to ensure all links have a length greater than 8 and a link label. Before, it was only checking for the link label.
