### ISSUE TITLE
CMS: Faculty Profile required bug

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/cms-college-main#44]
Selected WYSIWYG box for "Honors and Awards", requires items from sections further down on the same page

![Image](https://user-images.githubusercontent.com/16828076/186757040-409aa29b-7450-42b8-ba0b-0b2f5a58607a.png)

**Comment by lalov1** [comment]
I accidentally added the Accordion for Publications to appear, but I fixed it. Could you please try again?
